export const EVENTS = {
  EDIT_PLACE: 'EDIT_PLACE',
  SHOW_FILTERED_PLACES: 'SHOW_FILTERED_PLACES',
  OPEN_PLACE_FOR_EDITING: 'OPEN_PLACE_FOR_EDITING',
  REMOVED_PLACE: 'REMOVED_PLACE',
  SHOW_ALL_PLACES: 'SHOW_ALL_PLACES',
  REFRESH_PLACES: 'REFRESH_PLACES',
}